# docker-compose.yml
version: '3'
services:
  db:
    image: postgres:12.10-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6969:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local